spring.application.name=rfp_response_copilot

spring.datasource.url=jdbc:postgresql://localhost:5432/rfp_response_copilot_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.elasticsearch.uris=http://localhost:9200

spring.servlet.multipart.max-file-size=10MB
